Draft: Add support for Flatpak automatic generation
JamesMcCrae/flatfab pull request #20
Opened 2024-12-08 23:33 UTC by skadge

Flatpak (https://flatpak.org/) is becoming the dominant application distribution mechanism on Linuxes.

This PR:
- add supports for building FlatFab as a flatpak
- add a github workflow action to automatically build the flatpak

This PR is not complete yet:
- the resulting flatpak does not currently work due to a dynamic linking issue (`libGLU.so.1` inside of the flatbak container is not found, unclear why, a workaround would be to start FlatFab from a script that add `/app/lib64` to `LD_LIBRARY_PATH`)
- we should probably only run this workflow for tagged releases
- ideally, we should automatically publish the flatpak on flathub (https://flathub.org/) which is the leading 'app store' for open-source flatpaks. I haven't looked into it yet.

@JamesMcCrae please let me know if you think this is a useful direction, and if you feel like providing this kind of distribution channel (this would definitely make it much easier to install and update FlatFab on linux, without having to care too much about the different linux distributions)

2024-12-11 22:30 UTC, skadge commented
For reference, the generate binary is only ~1.5MB big! (this is possible as all the Qt libraries are manage by flatpak as shared runtimes, thus massively reducing the size of the package)

2024-12-12 15:54 UTC, JamesMcCrae requested changes
This seems like a great initiative, as it will streamline distribution of latest releases on Linux moving forward.  A few comments just relating to further removal of Network/Webengine from these automation files, and then happy to approve the changes.

2024-12-12 15:54 UTC, JamesMcCrae commented on CMakeLists.txt
> +find_package(Qt5 COMPONENTS Core Gui OpenGL Widgets Network REQUIRED)
Can "Network" also be removed here?

2024-12-12 15:54 UTC, JamesMcCrae commented on CMakeLists.txt
>      Qt5::Network
Remove "Qt5::Network" here?

2024-12-12 15:54 UTC, JamesMcCrae commented on README.md
> +- `flatpak install io.qt.qtwebengine.BaseApp/x86_64/5.15-24.08`
Should this line be removed, as it appears specific to webengine?

2024-12-12 16:10 UTC, JamesMcCrae commented
Re: GLU library issue, where does the Flatpak-generated build look for the library?  When I run "ldd FlatFab" locally I get:

	libGLU.so.1 => /lib/x86_64-linux-gnu/libGLU.so.1 (0x00007f5df29ef000)

2024-12-13 22:15 UTC, skadge commented on CMakeLists.txt
> +find_package(Qt5 COMPONENTS Core Gui OpenGL Widgets Network REQUIRED)
good catch. Fixed in #21

2024-12-13 22:16 UTC, skadge commented on CMakeLists.txt
>      Qt5::Network
same. Fixed in #21

2024-12-13 22:16 UTC, skadge commented on README.md
> +- `flatpak install io.qt.qtwebengine.BaseApp/x86_64/5.15-24.08`
fixed, thanks

2024-12-13 22:19 UTC, skadge commented
> Re: GLU library issue, where does the Flatpak-generated build look for the library? When I run "ldd FlatFab" locally I get:
> 
> ```
> libGLU.so.1 => /lib/x86_64-linux-gnu/libGLU.so.1 (0x00007f5df29ef000)
> ```

As you might have seen in the flatpak manifest, I build manually libGLU when building the flatpak. The library end up in `/app/lib64`. For some reason (and I could not figure out why), the FlatFab binary happily compiles against this library, but  fails to launch, as `/app/lib64` is not in the `LD_LIBRARY_PATH` of the built flatpak. So in `flatpak/flatfab-launch.sh`, I manually append this path the the `LD_LIBRARY_PATH` before launching FlatFab.

2024-12-13 23:34 UTC, skadge commented
@JamesMcCrae : I've renamed the flatpak id from `com.flatfab.FlatFab` to `edu.toronto.dgp.FlatFab`.

2024-12-15 16:42 UTC, JamesMcCrae approved these changes

2024-12-15 16:42 UTC, merged